version: '3.7'

services:
  wg-tunnel-server:
    image: ghcr.io/wg-easy/wg-easy:8-nightly
    container_name: wg-tunnel-server
    restart: unless-stopped
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
      - 7800:7800
      - 888:888
      - 80:80
      - 443:443
      - 20:20
      - 21:21
      - 3306:3306
      - 8929:8929
      - 2224:2224
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wg-config:/etc/wireguard
    environment:
      - WG_HOST=${SERVER_HOST}
      - PASSWORD=${SERVER_WG_PASSWORD:-123qwezxc}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS:-0.0.0.0/1}
      - WG_PRE_UP=iptables -t nat -A PREROUTING -p tcp -i eth0 --match multiport --destination-ports 7800,888,80,443,20,21,3306,8929,2224 -j DNAT --to-destination 10.8.0.2;
      - WG_PRE_DOWN=iptables -t nat -D PREROUTING -p tcp -i eth0 --match multiport --destination-ports 7800,888,80,443,20,21,3306,8929,2224 -j DNAT --to-destination 10.8.0.2;
